import {
  deepOrange,
  deepPurple,
  blue,
  blueGrey,
  green,
  grey,
  indigo,
  lightBlue,
  lightGreen,
  orange,
  pink,
  purple,
  red,
  yellow,
} from '@mui/material/colors';

export const avatarColors = {
  'deepOrange': deepOrange[500],
  'deepPurple': deepPurple[500],
  'blue': blue[500],
  'blueGrey': blueGrey[500],
  'green': green[500],
  'grey': grey[500],
  'indigo': indigo[500],
  'lightBlue': lightBlue[500],
  'lightGreen': lightGreen[500],
  'orange': orange[500],
  'pink': pink[500],
  'purple': purple[500],
  'red': red[500],
  'yellow': yellow[500],
};

export const userColors = [
  'deepOrange',
  'deepPurple',
  'blue',
  'blueGrey',
  'green',
  'grey',
  'indigo',
  'lightBlue',
  'lightGreen',
  'orange',
  'pink',
  'purple',
  'red',
  'yellow',
];
